name: Daily News Routine

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *' # This runs the workflow at 6:00 AM every day

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          FEEDS_FILE="feeds.txt"
          OUTPUT_DIR="$GITHUB_WORKSPACE/output"

          mkdir -p "$OUTPUT_DIR"

          while read url; do
            if [ -n "$url" ]; then
              echo "Processing Feed: $url"
              python3 rss2pdf.py "$url" "$OUTPUT_DIR"
            fi
          done < "$FEEDS_FILE"
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: daily-news-report
          path: .
