name: Daily News Routine

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *' # This runs the workflow at 6:00 AM every day

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: python -m playwright install --with-deps
        
      - name: Run script
        run: |
          FEEDS_FILE="Feeds.txt"
          OUTPUT_DIR="$GITHUB_WORKSPACE/output"
          mkdir -p "$OUTPUT_DIR"

          # normalise CRLF → LF
          sed -i 's/\r$//' "$FEEDS_FILE"

          while IFS= read -r raw || [ -n "$raw" ]; do
            url="${raw%%#*}"                       # strip comments
            url="$(printf '%s' "$url" | xargs)"    # trim
            if [[ -n "$url" && "$url" =~ ^https?:// ]]; then
              echo "Processing Feed: $url"
              python3 rss2pdf.py "$url" "$OUTPUT_DIR" || echo "::warning::Failed $url"
          fi
        done < "$FEEDS_FILE"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: daily-news-report
          path: output
